# This is a basic workflow to help you get started with Actions

name: Check Packages Version Updates 

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "main"
  main:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup git
        shell: cmd
        run: |
          git config user.name "CPVU bot"
          git config user.email "<>"

      - name: Run CPVU.exe
        shell: cmd
        run: |
          echo %cd%
          cd .\.github\workflows\CPVU

          mkdir _Temp_Thor

          echo Get Thor's Updates.zip
          curl https://raw.githubusercontent.com/VFPX/Thor/master/ThorUpdater/Updates.zip -o _Temp_Thor\Updates.zip
          tar -xf _Temp_Thor\Updates.zip -C _Temp_Thor

          .\cpvu.exe
          
          echo --------- CPVU.exe errors -----------
          type .\_TempErrorLog.txt
          echo -------------------------------------
          echo ------ Version File errors ----------
          type .\_TempThorUpdatesErrorLog.txt
          echo -------------------------------------

          git add ../../../Installers/foxgetpackages.*
          git commit -m "update foxgetpackages.dbf"
          git push
          
          echo End of Run CPVU.exe

          
